165825297 reprezentacja botów w systemie
adinef/ZZPJ-bot-site pull request #2
Opened 2019-05-15 21:25 UTC by kacperpradzynski

First Bot entity implementation

2019-05-15 21:45 UTC, adinef requested changes
Parę rzeczy i w sumie można robić **merge**.

2019-05-15 21:45 UTC, adinef commented on src/main/java/pl/lodz/p/it/zzpj/botsite/exceptions/BotAlreadyExistsException.java
> +
Dodaj jeszcze przynajmniej konstruktory z innym exception (zagnieżdżanie) oraz message + exception.

2019-05-15 21:45 UTC, adinef commented on src/main/java/pl/lodz/p/it/zzpj/botsite/exceptions/UsernameAlreadyExistsException.java
> +public class UsernameAlreadyExistsException extends Exception {
Tak jak wcześniej.

2019-05-15 21:45 UTC, adinef commented on src/main/java/pl/lodz/p/it/zzpj/botsite/services/BotServiceImpl.java
> +    public Bot findById(String id) throws BotRetrievalException {
Nie jest to wymagane ze strony jezyka, ale dodawaj @Override nad metodami nadpisanymi - ułatwia nieco czytanie i rozóżnienie.

2019-05-15 21:45 UTC, adinef commented on src/main/java/pl/lodz/p/it/zzpj/botsite/web/controllers/BotController.java
> +    @PostMapping("/newBot")
post bez osobnej ścieżki, niech uderza na /

2019-05-15 21:45 UTC, adinef commented on src/main/java/pl/lodz/p/it/zzpj/botsite/web/controllers/UserController.java
> +    @PostMapping("/newUser")
tak samo jak wyżej

2019-05-15 21:45 UTC, adinef commented on src/main/java/pl/lodz/p/it/zzpj/botsite/web/controllers/UserController.java
> +    ModelMapper modelMapper = new ModelMapper();
Stwórz osobną klasę, która ma @Bean na ModelMapper.

2019-05-15 21:45 UTC, adinef commented on src/test/java/pl/lodz/p/it/zzpj/botsite/web/controllers/UserControllerTest.java
> +    private ModelMapper modelMapper = new ModelMapper();
Tak jak pisałem, @Bean na to :)

2019-05-16 14:05 UTC, kacperpradzynski commented
Ten rzeczy odnośnie usera to chyba wywalę z tego brancha, bo zrobiłem niepotrzebnie marga do mnie od Dominika :P

2019-05-16 18:00 UTC, adinef commented
@Gnlknmd po prostu poprawi u siebie przed PR.

2019-05-17 10:59 UTC, merged